version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db 
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
        - 3306:3306
        - 33060:33060

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
        - mysql
